@startuml
!include _common.style

title Takenoko (Structure)
center footer project #2 - class diagram

package uqam.inf5153.game{

  package joueur{
    class Joueur{
      - score: int
      - nbrActions: int
    }
    class PlateauDuJoueur{

    }
    Joueur *--> PlateauDuJoueur
    Joueur *--> Objectif
  }

  package parcelle{
    abstract class Parcelle{

    }
    class ParcelleVerte{

    }
    class ParcelleJaune{

    }
    class ParcelleRose{

    }
    class ParcelleEtang{

    }
    abstract class Bambou {

    }

    class BambouVerte{

    }

    class BambouJaune {

    }

    class BambouJaune {

    }

    ParcelleVerte --|> Parcelle
    ParcelleJaune --|> Parcelle
    ParcelleRose --|> Parcelle
    ParcelleEtang --|> Parcelle
    Parcelle *--> "1-4"Bambou
    BambouJaune --|> Bambou
    BambouVerte --|> Bambou
    BambouRose --|> Bambou

  }

  package objectif{
    abstract class Objectif{
      points : int
    }
    class ObjectifParcelle{

    }
    ObjectifParcelle --|> Objectif
  }


}

@enduml