@startuml
!include _common.style
title Initialisation Takenoko (déroulement)

participant "Takenoko" as T
participant "jeu: Jeu" as J
participant "pJeu: PlateauDeJeu" as PJeu
participant "pJoueur: PlateauDeJoueur" as PJoueur
participant "pObj: PiocheObjectifs" as pObj
participant "pPar: PiocheParcelles" as pPar
participant "joueur: Joueur" as Joueur

activate T
T -> J : this()
loop for i = 0; i < 2; i++
    activate J
    J -> Joueur: this()
    activate Joueur
    Joueur --> PJoueur: this()
    deactivate Joueur
    activate PJoueur
end
J -> PJeu: this()
activate PJeu
J -> pObj : this()
activate pObj
J -> pPar: this()
activate pPar


pPar --> J
deactivate pPar




pObj --> J
deactivate pObj
deactivate PJoueur

PJeu --> J
deactivate PJeu
J --> T
deactivate J
deactivate T


center footer project #2 - initialisation sequence diagram
@enduml